services:
  api:
    build: .
    container_name: go-api
    ports:
      - "3001:3001"
    environment:
      - GO_ENV=production
      - PORT=3001
      - DATABASE_URL=postgres://user:pass@db:5432/app
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: go-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app
    ports:
      - "5433:5432"
